'use strict';

(function () {
  var NUMBER_OF_POSTS = 25;
  var MIN_LIKES_VALUE = 15;
  var MAX_LIKES_VALUE = 200;
  var MIN_AVATAR_NUMBER = 1;
  var MAX_AVATAR_NUMBER = 6;
  var MIN_COMMENTS_NUMBER = 1;
  var MAX_COMMENTS_NUMBER = 10;
  var COMMENT_AVATAR_WIDTH = 35;
  var COMMENT_AVATAR_HEIGHT = 35;
  var SCALE_STEP = 25;
  var MIN_SCALE = 25;
  var MAX_SCALE = 100;
  var MAX_PERCENT = 100;
  var START_PIN_POSITION = 0;
  var EFFECT_LINE_LENGTH = 453;
  var END_PIN_POSITION = START_PIN_POSITION + EFFECT_LINE_LENGTH;
  var HASHTAG_MAX_LENGTH = 20;
  var MAX_NUM_OF_TAGS = 5;

  window.constants = {
    NUMBER_OF_POSTS: NUMBER_OF_POSTS,
    MIN_LIKES_VALUE: MIN_LIKES_VALUE,
    MAX_LIKES_VALUE: MAX_LIKES_VALUE,
    MIN_AVATAR_NUMBER: MIN_AVATAR_NUMBER,
    MAX_AVATAR_NUMBER: MAX_AVATAR_NUMBER,
    MIN_COMMENTS_NUMBER: MIN_COMMENTS_NUMBER,
    MAX_COMMENTS_NUMBER: MAX_COMMENTS_NUMBER,
    COMMENT_AVATAR_WIDTH: COMMENT_AVATAR_WIDTH,
    COMMENT_AVATAR_HEIGHT: COMMENT_AVATAR_HEIGHT,
    START_PIN_POSITION: START_PIN_POSITION,
    END_PIN_POSITION: END_PIN_POSITION,
    EFFECT_LINE_LENGTH: EFFECT_LINE_LENGTH,
    SCALE_STEP: SCALE_STEP,
    MIN_SCALE: MIN_SCALE,
    MAX_SCALE: MAX_SCALE,
    MAX_PERCENT: MAX_PERCENT,
    HASHTAG_MAX_LENGTH: HASHTAG_MAX_LENGTH,
    MAX_NUM_OF_TAGS: MAX_NUM_OF_TAGS
  };
})();
