'use strict';

(function () {
  const NUMBER_OF_POSTS = 25;
  const MIN_LIKES_VALUE = 15;
  const MAX_LIKES_VALUE = 200;
  const MIN_AVATAR_NUMBER = 1;
  const MAX_AVATAR_NUMBER = 6;
  const MIN_COMMENTS_NUMBER = 1;
  const MAX_COMMENTS_NUMBER = 10;
  const COMMENT_AVATAR_WIDTH = 35;
  const COMMENT_AVATAR_HEIGHT = 35;
  const SCALE_STEP = 25;
  const MIN_SCALE = 25;
  const MAX_SCALE = 100;
  const MAX_PERCENT = 100;
  const START_PIN_POSITION = 0;
  const EFFECT_LINE_LENGTH = 453;
  const END_PIN_POSITION = START_PIN_POSITION + EFFECT_LINE_LENGTH;
  const HASHTAG_MAX_LENGTH = 20;
  const MAX_NUM_OF_TAGS = 5;

  window.constants = {
    NUMBER_OF_POSTS,
    MIN_LIKES_VALUE,
    MAX_LIKES_VALUE,
    MIN_AVATAR_NUMBER,
    MAX_AVATAR_NUMBER,
    MIN_COMMENTS_NUMBER,
    MAX_COMMENTS_NUMBER,
    COMMENT_AVATAR_WIDTH,
    COMMENT_AVATAR_HEIGHT,
    START_PIN_POSITION,
    END_PIN_POSITION,
    EFFECT_LINE_LENGTH,
    SCALE_STEP,
    MIN_SCALE,
    MAX_SCALE,
    MAX_PERCENT,
    HASHTAG_MAX_LENGTH,
    MAX_NUM_OF_TAGS
  };
})();
